# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GoPartner Support
tool: GoPartner
email: support@bizongo.com
description: Support
logo: "/assets/logo.ico"
image: "/assets/gopartner-icon.png"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://partnerhelp.bizongo.com" # the base hostname & protocol for your site, e.g. http://example.com

contact_us: "mailto:product@bizongo.com"
search: Search for anything (quotes, timelines, ratings or payments) ... # the placeholder search in the front page


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


# collections in the site
collections:
   projects:
      output: true
      permalink: "/:title"
   faqs:
      output: true
      permalink: "/:title"



# default layouts for pages
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
      author: "Jakir Hassan"
  -
    scope:
      path: ""
      type: "faqs"
    values:
      layout: "article"
      author: "Jakir Hassan"




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
